### ISSUE TITLE
No External ip for service

### ISSUE THREAD

**Issue by veris-neerajdhiman** [hnarayanan/kubernetes-django#12]
- When I ran ` kubectl get svc` , I got all services but their was no External ip assigned to my service.
- So how can I ran the dev server of my app ? 
```
app              10.0.0.204   <pending>     80:31987/TCP     17h
```

**Comment by hnarayanan** [comment]
Are you attempting to run this locally? And if so how?

You underlying infrastructure needs to have a mechanism to setup this external IP. It comes out of the box in cloud services like GKE and AWS, but is not obvious when e.g. you install Kubernetes on a local virtual machine.

**Comment by veris-neerajdhiman** [comment]
@hnarayanan yes I am runing kubernetes locally and pulled you django project image .

**Comment by hnarayanan** [comment]
This is non-trivial. You need to understand something called `Ingress` in Kubernetes (https://kubernetes.io/docs/concepts/services-networking/ingress/) and set it up on your local machine.

I am going to close this issue because this is beyond the scope of this simple tutorial (that primarily focusses on the Django bits), but please re-open this issue later if you're really struggling.

Or even better, contribute back detailed instructions on how you figured this out! 😃
